
name: Deploy github pages

on:
  push:
    branches: ["main"]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install
        run: npm i
      - name: build
        run: npm run build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
